# Generated by Django 5.2.4 on 2025-08-09 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barangay', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dropoff_sites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20)),
                ('question', models.TextField()),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(max_length=10)),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'quizzes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.TextField()),
                ('user_type', models.CharField(max_length=10)),
                ('barangay', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField()),
                ('account_status', models.CharField(max_length=10)),
                ('registered_by_admin', models.BooleanField()),
                ('weekly_bonus_given', models.DateField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qr_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bottle_data', models.JSONField(default=list)),
                ('total_points', models.IntegerField()),
                ('source', models.CharField(default='manual', max_length=20)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('estimated_quantity', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropoff_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dashboard.dropoffsite')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to='dashboard.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dashboard.user')),
            ],
            options={
                'db_table': 'submissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StaffTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(default='submission_made', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='dashboard.submission')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_transactions', to='dashboard.user')),
            ],
            options={
                'db_table': 'staff_transactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=20)),
                ('telco', models.CharField(max_length=10)),
                ('points_used', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('date_requested', models.DateTimeField()),
                ('date_processed', models.DateTimeField(null=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rewards', to='dashboard.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
            options={
                'db_table': 'reward_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('daily', 'Daily Quiz'), ('weekly', 'Weekly Quiz')], max_length=10)),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('points_awarded', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='dashboard.user')),
            ],
            options={
                'db_table': 'quiz_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField()),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='dashboard.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='dashboard.user')),
            ],
            options={
                'db_table': 'quiz_answers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dropoffsite',
            name='assigned_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_site', to='dashboard.user'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=100)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='dashboard.user')),
            ],
            options={
                'db_table': 'user_badges',
                'managed': True,
            },
        ),
    ]
