# Generated by Django 5.2.4 on 2025-09-23 04:16

import dashboard.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIYDailyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'diy_daily_pools',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DIYTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Instructions and materials list.')),
                ('video_url', models.URLField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='diy_thumbs/')),
                ('points_on_submit', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diy_tutorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('small_bottle_points', models.PositiveIntegerField(default=5, help_text='Points per SMALL bottle', validators=[django.core.validators.MinValueValidator(0)])),
                ('large_bottle_points', models.PositiveIntegerField(default=10, help_text='Points per LARGE bottle', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'points_config',
            },
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(default='Tacloban City', max_length=150)),
            ],
            options={
                'db_table': 'barangays',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='uniq_barangay_name_city')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('registered_by_admin', models.BooleanField(default=False)),
                ('weekly_bonus_given', models.DateField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dashboard.barangay')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DIYSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diy_submissions/')),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('is_public', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diy_submissions', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submissions', to='dashboard.diytutorial')),
            ],
            options={
                'db_table': 'diy_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DIYDailySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='dashboard.diydailypool')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_selections', to='dashboard.diytutorial')),
            ],
            options={
                'db_table': 'diy_daily_selections',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='diydailypool',
            name='tutorials',
            field=models.ManyToManyField(related_name='daily_pools', to='dashboard.diytutorial'),
        ),
        migrations.CreateModel(
            name='DropOffSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_site', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_site', to='dashboard.barangay')),
            ],
            options={
                'db_table': 'dropoff_sites',
            },
        ),
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('telco', models.CharField(choices=[('globe', 'Globe'), ('smart', 'Smart'), ('dito', 'DITO'), ('other', 'Other')], default='other', max_length=10)),
                ('points_used', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_rewards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reward_requests',
                'ordering': ['-date_requested'],
            },
        ),
        migrations.CreateModel(
            name='StaffApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_staff_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.barangay')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_data', models.JSONField(blank=True, default=list)),
                ('proposed_points', models.PositiveIntegerField(default=0)),
                ('claimed_points', models.PositiveIntegerField(default=0)),
                ('qr_token', models.CharField(default=dashboard.models.generate_qr_token, editable=False, max_length=64, unique=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('voided', 'Voided')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('vision', 'Vision')], default='manual', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_submissions', to=settings.AUTH_USER_MODEL)),
                ('dropoff_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='dashboard.dropoffsite')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='submission_created', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_transactions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='dashboard.submission')),
            ],
            options={
                'db_table': 'staff_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('submission_claim', 'Submission Claim'), ('diy_submit', 'DIY Submission'), ('adjustment', 'Adjustment')], max_length=20)),
                ('delta_points', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='dashboard.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_points_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile_number'], name='users_mobile__68fe34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diysubmission',
            unique_together={('user', 'tutorial')},
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['status'], name='reward_requ_status_366255_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['date_requested'], name='reward_requ_date_re_c63bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['mobile_number'], name='reward_requ_mobile__728038_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['qr_token'], name='submissions_qr_toke_711255_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='submissions_created_ff86d7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['claimed_by'], name='submissions_claimed_42eed8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['dropoff_site'], name='submissions_dropoff_81198c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpointsledger',
            index=models.Index(fields=['user', 'created_at'], name='user_points_user_id_845688_idx'),
        ),
    ]
