# Generated by Django 5.2.4 on 2025-10-11 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropoffsite',
            name='assigned_staff',
        ),
        migrations.AddField(
            model_name='dropoffsite',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
