# Generated by Django 5.2.4 on 2025-10-12 06:08

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0002_remove_dropoffsite_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diydailyselection',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='3–20 chars; start with a letter; letters, numbers, and underscores only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must start with a letter and contain only letters, numbers, or underscores (3–20 chars).', regex='^[A-Za-z][A-Za-z0-9_]{2,19}$')]),
        ),
        migrations.AddConstraint(
            model_name='diydailyselection',
            constraint=models.UniqueConstraint(fields=('date', 'tutorial'), name='uniq_daily_tutorial'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_users_username_ci'),
        ),
    ]
