# Generated by Django 5.2.4 on 2025-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_diydailyselection_date_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diysubmission',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='diysubmission',
            constraint=models.UniqueConstraint(fields=('user', 'tutorial'), name='uniq_user_tutorial'),
        ),
    ]
