# Generated by Django 5.2.4 on 2025-10-15 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_diysubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrequest',
            name='custom_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='operator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='operator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='reloadly_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardrequest',
            name='reloadly_tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='PH mobile must be local format 09XXXXXXXXX (11 digits).', regex='^0\\d{10}$')]),
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['mobile_number', 'amount', 'status', 'date_requested'], name='rwreq_webhook_match_idx'),
        ),
    ]
