# Generated by Django 5.2.4 on 2025-10-23 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rewardrequest_custom_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('items', models.JSONField(blank=True, default=list)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vision_detection_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='diysubmission',
            name='uniq_user_tutorial',
        ),
        migrations.AddIndex(
            model_name='diysubmission',
            index=models.Index(fields=['user', 'tutorial', 'created_at'], name='diy_submiss_user_id_2768f7_idx'),
        ),
        migrations.AddField(
            model_name='detectionsession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
