# Generated by Django 5.2.4 on 2025-10-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_detectionsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diysubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='diysubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diy_submissions/'),
        ),
    ]
