# Generated by Django 5.2.4 on 2026-01-01 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_diysubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsconfig',
            name='points_per_peso',
            field=models.PositiveIntegerField(default=10, help_text='How many points equal 1 PHP (e.g., 10 means 10 points = ₱1).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
